"""system settings

Revision ID: 9501dbd3d7b1
Revises: b2c9f71cc991
Create Date: 2026-09-02 15:59:50.065563+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9501dbd3d7b1'
down_revision = 'b2c9f71cc991'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=160), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('balance_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allow_shop_edit_after_submit', sa.Boolean(), nullable=False),
    sa.Column('lock_records_after_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
