"""initial schema

Revision ID: b2c9f71cc991
Revises: 
Create Date: 2026-09-02 15:48:31.968314+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b2c9f71cc991'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bale_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('weight_lbs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bale_types')),
    sa.UniqueConstraint('code', name=op.f('uq_bale_types_code'))
    )
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parser_key', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banks')),
    sa.UniqueConstraint('code', name=op.f('uq_banks_code'))
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('name', name=op.f('uq_cities_name'))
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_currencies'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'run_after'], unique=False)
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_table('match_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_window_days', sa.Integer(), nullable=False),
    sa.Column('amount_tolerance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('auto_confirm_score', sa.Integer(), nullable=False),
    sa.Column('suggest_score', sa.Integer(), nullable=False),
    sa.Column('auto_confirm_requires_unique', sa.Boolean(), nullable=False),
    sa.Column('match_debit_transactions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_settings'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('fk_bank_accounts_bank_id_banks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_bank_accounts_currency_code_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts')),
    sa.UniqueConstraint('bank_id', 'account_number', name='uq_bank_accounts_bank_id_account_number')
    )
    op.create_index(op.f('ix_bank_accounts_bank_id'), 'bank_accounts', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_currency_code'), 'bank_accounts', ['currency_code'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_shops_city_id_cities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops')),
    sa.UniqueConstraint('code', name=op.f('uq_shops_code'))
    )
    op.create_index(op.f('ix_shops_city_id'), 'shops', ['city_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('record_type', sa.String(length=48), nullable=True),
    sa.Column('record_id', sa.String(length=48), nullable=True),
    sa.Column('summary', sa.String(length=400), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index('ix_audit_logs_record', 'audit_logs', ['record_type', 'record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bank_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_key', sa.String(length=400), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('parser_key', sa.String(length=32), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('statement_opening_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('statement_closing_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_bank_statements_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_bank_statements_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_statements')),
    sa.UniqueConstraint('bank_account_id', 'file_hash', name='uq_bank_statements_account_file')
    )
    op.create_index(op.f('ix_bank_statements_bank_account_id'), 'bank_statements', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_statements_deleted_at'), 'bank_statements', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bank_statements_file_hash'), 'bank_statements', ['file_hash'], unique=False)
    op.create_index('ix_bank_statements_period', 'bank_statements', ['period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_bank_statements_status'), 'bank_statements', ['status'], unique=False)
    op.create_table('shop_daily_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bale_count', sa.Integer(), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('total_sales_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_sales_nio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('delivery_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('delivery_nio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commercial_invoice_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commercial_invoice_nio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_nio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opening_balance_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opening_balance_nio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance_nio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance_source', sa.String(length=16), nullable=False),
    sa.Column('observations', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bale_count >= 0', name=op.f('ck_shop_daily_records_bale_count_non_negative')),
    sa.CheckConstraint('invoice_count >= 0', name=op.f('ck_shop_daily_records_invoice_count_non_negative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_shop_daily_records_created_by_id_users')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_daily_records_shop_id_shops')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_shop_daily_records_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_daily_records'))
    )
    op.create_index('ix_shop_daily_records_business_date', 'shop_daily_records', ['business_date'], unique=False)
    op.create_index(op.f('ix_shop_daily_records_deleted_at'), 'shop_daily_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_shop_daily_records_shop_id'), 'shop_daily_records', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_daily_records_status'), 'shop_daily_records', ['status'], unique=False)
    op.create_index('uq_shop_daily_records_shop_date_live', 'shop_daily_records', ['shop_id', 'business_date'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('user_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_user_shops_shop_id_shops'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_shops_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_shops')),
    sa.UniqueConstraint('user_id', 'shop_id', name='uq_user_shops_user_id_shop_id')
    )
    op.create_index(op.f('ix_user_shops_shop_id'), 'user_shops', ['shop_id'], unique=False)
    op.create_index(op.f('ix_user_shops_user_id'), 'user_shops', ['user_id'], unique=False)
    op.create_table('bale_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_record_id', sa.Integer(), nullable=False),
    sa.Column('bale_type_id', sa.Integer(), nullable=False),
    sa.Column('opening_qty', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('sold_qty', sa.Integer(), nullable=False),
    sa.Column('closing_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bale_type_id'], ['bale_types.id'], name=op.f('fk_bale_records_bale_type_id_bale_types')),
    sa.ForeignKeyConstraint(['daily_record_id'], ['shop_daily_records.id'], name=op.f('fk_bale_records_daily_record_id_shop_daily_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bale_records'))
    )
    op.create_index(op.f('ix_bale_records_daily_record_id'), 'bale_records', ['daily_record_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('movement_type', sa.String(length=16), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Integer(), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.Column('ignored_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('CREDIT','DEBIT')", name=op.f('ck_bank_transactions_direction_valid')),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name=op.f('ck_bank_transactions_amounts_non_negative')),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_bank_transactions_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('fk_bank_transactions_bank_id_banks')),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_bank_transactions_currency_code_currencies')),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], name=op.f('fk_bank_transactions_statement_id_bank_statements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_transactions')),
    sa.UniqueConstraint('bank_account_id', 'dedupe_hash', name='uq_bank_transactions_account_dedupe')
    )
    op.create_index('ix_bank_transactions_account_date', 'bank_transactions', ['bank_account_id', 'txn_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_amount'), 'bank_transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_bank_id'), 'bank_transactions', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_currency_code'), 'bank_transactions', ['currency_code'], unique=False)
    op.create_index(op.f('ix_bank_transactions_direction'), 'bank_transactions', ['direction'], unique=False)
    op.create_index(op.f('ix_bank_transactions_external_id'), 'bank_transactions', ['external_id'], unique=False)
    op.create_index('ix_bank_transactions_match_lookup', 'bank_transactions', ['currency_code', 'amount', 'txn_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_reference'), 'bank_transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_bank_transactions_statement_id'), 'bank_transactions', ['statement_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_txn_date'), 'bank_transactions', ['txn_date'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_record_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_expenses_amount_non_negative')),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_expenses_currency_code_currencies')),
    sa.ForeignKeyConstraint(['daily_record_id'], ['shop_daily_records.id'], name=op.f('fk_expenses_daily_record_id_shop_daily_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_daily_record_id'), 'expenses', ['daily_record_id'], unique=False)
    op.create_table('shop_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_record_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('deposit_time', sa.Time(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.Column('ignored_reason', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_shop_transfers_amount_positive')),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_shop_transfers_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('fk_shop_transfers_bank_id_banks')),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_shop_transfers_currency_code_currencies')),
    sa.ForeignKeyConstraint(['daily_record_id'], ['shop_daily_records.id'], name=op.f('fk_shop_transfers_daily_record_id_shop_daily_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_transfers'))
    )
    op.create_index(op.f('ix_shop_transfers_bank_account_id'), 'shop_transfers', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_shop_transfers_bank_id'), 'shop_transfers', ['bank_id'], unique=False)
    op.create_index(op.f('ix_shop_transfers_currency_code'), 'shop_transfers', ['currency_code'], unique=False)
    op.create_index(op.f('ix_shop_transfers_daily_record_id'), 'shop_transfers', ['daily_record_id'], unique=False)
    op.create_index(op.f('ix_shop_transfers_deleted_at'), 'shop_transfers', ['deleted_at'], unique=False)
    op.create_index('ix_shop_transfers_lookup', 'shop_transfers', ['currency_code', 'amount', 'bank_id'], unique=False)
    op.create_index(op.f('ix_shop_transfers_reference'), 'shop_transfers', ['reference'], unique=False)
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_transfer_id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('amount_delta', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('date_delta_days', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('matched_by_id', sa.Integer(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unmatched_by_id', sa.Integer(), nullable=True),
    sa.Column('unmatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('CONFIRMED','SUGGESTED','REJECTED')", name=op.f('ck_reconciliation_matches_status_valid')),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name=op.f('ck_reconciliation_matches_confidence_range')),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], name=op.f('fk_reconciliation_matches_bank_transaction_id_bank_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_by_id'], ['users.id'], name=op.f('fk_reconciliation_matches_matched_by_id_users')),
    sa.ForeignKeyConstraint(['shop_transfer_id'], ['shop_transfers.id'], name=op.f('fk_reconciliation_matches_shop_transfer_id_shop_transfers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unmatched_by_id'], ['users.id'], name=op.f('fk_reconciliation_matches_unmatched_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_matches'))
    )
    op.create_index('ix_recon_status', 'reconciliation_matches', ['status', 'is_active'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_bank_transaction_id'), 'reconciliation_matches', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_shop_transfer_id'), 'reconciliation_matches', ['shop_transfer_id'], unique=False)
    op.create_index('uq_recon_active_bank_txn', 'reconciliation_matches', ['bank_transaction_id'], unique=True, postgresql_where="is_active AND status = 'CONFIRMED'")
    op.create_index('uq_recon_active_transfer', 'reconciliation_matches', ['shop_transfer_id'], unique=True, postgresql_where="is_active AND status = 'CONFIRMED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_recon_active_transfer', table_name='reconciliation_matches', postgresql_where="is_active AND status = 'CONFIRMED'")
    op.drop_index('uq_recon_active_bank_txn', table_name='reconciliation_matches', postgresql_where="is_active AND status = 'CONFIRMED'")
    op.drop_index(op.f('ix_reconciliation_matches_shop_transfer_id'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_bank_transaction_id'), table_name='reconciliation_matches')
    op.drop_index('ix_recon_status', table_name='reconciliation_matches')
    op.drop_table('reconciliation_matches')
    op.drop_index(op.f('ix_shop_transfers_reference'), table_name='shop_transfers')
    op.drop_index('ix_shop_transfers_lookup', table_name='shop_transfers')
    op.drop_index(op.f('ix_shop_transfers_deleted_at'), table_name='shop_transfers')
    op.drop_index(op.f('ix_shop_transfers_daily_record_id'), table_name='shop_transfers')
    op.drop_index(op.f('ix_shop_transfers_currency_code'), table_name='shop_transfers')
    op.drop_index(op.f('ix_shop_transfers_bank_id'), table_name='shop_transfers')
    op.drop_index(op.f('ix_shop_transfers_bank_account_id'), table_name='shop_transfers')
    op.drop_table('shop_transfers')
    op.drop_index(op.f('ix_expenses_daily_record_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_bank_transactions_txn_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_statement_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_reference'), table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_match_lookup', table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_external_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_direction'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_currency_code'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_amount'), table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_account_date', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_bale_records_daily_record_id'), table_name='bale_records')
    op.drop_table('bale_records')
    op.drop_index(op.f('ix_user_shops_user_id'), table_name='user_shops')
    op.drop_index(op.f('ix_user_shops_shop_id'), table_name='user_shops')
    op.drop_table('user_shops')
    op.drop_index('uq_shop_daily_records_shop_date_live', table_name='shop_daily_records', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_shop_daily_records_status'), table_name='shop_daily_records')
    op.drop_index(op.f('ix_shop_daily_records_shop_id'), table_name='shop_daily_records')
    op.drop_index(op.f('ix_shop_daily_records_deleted_at'), table_name='shop_daily_records')
    op.drop_index('ix_shop_daily_records_business_date', table_name='shop_daily_records')
    op.drop_table('shop_daily_records')
    op.drop_index(op.f('ix_bank_statements_status'), table_name='bank_statements')
    op.drop_index('ix_bank_statements_period', table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_file_hash'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_deleted_at'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_bank_account_id'), table_name='bank_statements')
    op.drop_table('bank_statements')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_record', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shops_city_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_bank_accounts_currency_code'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_bank_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('match_settings')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('currencies')
    op.drop_table('cities')
    op.drop_table('banks')
    op.drop_table('bale_types')
    # ### end Alembic commands ###
