"""paper sheet: bank totals, photos, dollar lines

Revision ID: d7a3e9b1c2f4
Revises: c4e1a7d20f53
Create Date: 2026-10-06 14:38:35.797275+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd7a3e9b1c2f4'
down_revision = 'c4e1a7d20f53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_record_id', sa.Integer(), nullable=True),
    sa.Column('stored_key', sa.String(length=400), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_model', sa.String(length=80), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_record_id'], ['shop_daily_records.id'], name=op.f('fk_sheet_photos_daily_record_id_shop_daily_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_sheet_photos_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheet_photos'))
    )
    op.create_index(op.f('ix_sheet_photos_daily_record_id'), 'sheet_photos', ['daily_record_id'], unique=False)
    op.create_table('shop_bank_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_record_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_shop_bank_totals_amount_positive')),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('fk_shop_bank_totals_bank_id_banks')),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_shop_bank_totals_currency_code_currencies')),
    sa.ForeignKeyConstraint(['daily_record_id'], ['shop_daily_records.id'], name=op.f('fk_shop_bank_totals_daily_record_id_shop_daily_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_bank_totals'))
    )
    op.create_index(op.f('ix_shop_bank_totals_daily_record_id'), 'shop_bank_totals', ['daily_record_id'], unique=False)
    op.create_index('uq_shop_bank_totals_cell', 'shop_bank_totals', ['daily_record_id', 'bank_id', 'currency_code'], unique=True)
    op.add_column('shop_daily_records', sa.Column('commercial_invoice_cash_usd', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('shop_daily_records', sa.Column('commercial_invoice_deposit_usd', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('shop_daily_records', sa.Column('delivery_cash_usd', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('shop_daily_records', sa.Column('delivery_transfer_usd', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('shop_daily_records', sa.Column('declared_closing_usd', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('shop_transfers', sa.Column('source', sa.String(length=16), server_default='SHEET', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_transfers', 'source')
    op.drop_column('shop_daily_records', 'declared_closing_usd')
    op.drop_column('shop_daily_records', 'delivery_transfer_usd')
    op.drop_column('shop_daily_records', 'delivery_cash_usd')
    op.drop_column('shop_daily_records', 'commercial_invoice_deposit_usd')
    op.drop_column('shop_daily_records', 'commercial_invoice_cash_usd')
    op.drop_index('uq_shop_bank_totals_cell', table_name='shop_bank_totals')
    op.drop_index(op.f('ix_shop_bank_totals_daily_record_id'), table_name='shop_bank_totals')
    op.drop_table('shop_bank_totals')
    op.drop_index(op.f('ix_sheet_photos_daily_record_id'), table_name='sheet_photos')
    op.drop_table('sheet_photos')
    # ### end Alembic commands ###
